services:
  - type: web
    name: fantasyedge-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:5000 app.api:app"
    region: oregon
    plan: free
